version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/server.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./symfony:/var/www/html

  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./symfony:/var/www/html